baseURL: "https://haru2175.github.io/"
languageCode: "ko"
title: "Design Studio Portfolio"

params:
  description: "Creative Design Studio Portfolio"

markup:
  highlight:
    style: github

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Members"
      url: "/Members/"
      weight: 2
    - name: "Education"
      url: "/Education/"
      weight: 3
    - name: "Publications"
      url: "/Publications/"
      weight: 3
    - name: "Posts"
      url: "/Posts/"
      weight: 4
