baseURL: "https://haru2175.github.io/"
languageCode: "ko"
title: "Hugo Theme Stack"
theme: "roxo-hugo"  # 사용할 테마 이름
menu:
  nav:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Contact"
      url: "/contact/"
      weight: 3
    - name: "Blog"
      url: "/blog/"
      weight: 4
    - name: "Tags"
      url: "/tags/"
      weight: 5
    - name: "Categories"
      url: "/categories/"
      weight: 6
